version: "2"

services:
    consumer:
        image: rabbit-consumer
        build: ./consumer
        networks:
            - backend
        restart: always

    rabbit:
        image: rabbitmq
        networks:
            - backend

    redis:
        image: redis
        networks:
            - backend

networks:
    backend:

